"""
This file ocntains the unit tests for the WebScraper class in web_Scraper.py.
"""


from urllib import request
from fixedIncome.src.web_scraper.web_scraper import WebScraper

#-----------------------------------------------------------------------------

web_scraper = WebScraper()

def test_valid_urls():
    """
    Tests if the generated url string for accessing the Treasury Direct API for us_treasury_instruments data is valid.
    Tests if the headers generated by each url is non-empty.
    """
    urls = [web_scraper.get_url(asset) for asset in web_scraper.types]
    headers_exist = []

    for url in urls:
        with request.urlopen(url) as url_opener:
            headers_exist.append(bool(url_opener.headers))  # tests if non-empty

    assert all(headers_exist)

